from __future__ import annotations

from typing import Protocol, Any


class CacheRepositoryProtocol(Protocol):
    """
    Назначение/ответственность:
        Порт доступа к локальному кэшу (репозиторий).
    Взаимодействия:
        Используется cache-refresh и cache-command usecases.
    Примечание:
        Временный компромисс: методы остаются dataset-specific (users/orgs).
    """

    def ensure_schema(self) -> None: ...

    def begin(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...

    def upsert_user(self, user_row: dict[str, Any]) -> str: ...
    def upsert_org(self, org_row: dict[str, Any]) -> str: ...

    def clear_users(self) -> int: ...
    def clear_orgs(self) -> int: ...

    def get_counts(self) -> tuple[int, int]: ...

    def get_meta(self, key: str) -> str | None: ...
    def set_meta(self, key: str, value: str | None) -> None: ...
