@startuml
set namespaceSeparator none
skinparam componentStyle rectangle
skinparam backgroundColor white
skinparam linetype ortho
skinparam defaultFontName Arial
skinparam component {
  BackgroundColor #f7e9dc
  BorderColor #d9c2a8
}

component "Bootstrap / Composition Root" as boot

component "CoreCatalog" as core
component "SourceCatalog\n(CSV, IO)" as src
component "SinkCatalog\n(HTTP/API)" as sink
component "DatasetCatalog\n(Employees)" as emp

component "ErrorCatalog" as catalog
component "DiagnosticFactory" as factory
component "DiagnosticContext" as ctx
component "Translator" as translator
component "HttpMapping" as httpmap
component "Policies\n(Retry/Stop/Exit + map_system_code)" as policy
component "DiagnosticBoundary" as boundary

boot --> core
boot --> src
boot --> sink
boot --> emp

core --> catalog
src --> catalog
sink --> catalog
emp --> catalog

catalog --> factory
factory --> ctx
catalog --> translator
httpmap --> translator
catalog --> policy
policy --> translator

translator --> boundary
ctx --> boundary
@enduml
