"""
Назначение:
    Базовый каталог диагностик ядра.
"""

from __future__ import annotations

from connector.domain.diagnostics.catalog import CatalogEntry, ErrorCatalog
from connector.domain.diagnostics.policies import SystemErrorCode
from connector.domain.models import DiagnosticSeverity


def build_core_catalog(*, strict: bool) -> ErrorCatalog:
    """
    Назначение:
        Сформировать базовый каталог диагностических кодов.
    """
    entries = [
        CatalogEntry("SOURCE_ERROR", SystemErrorCode.IO_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("missing_source_column", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("DSL_REGISTRY_INVALID", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("DSL_OP_UNKNOWN", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("DSL_OP_FAILED", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SOURCE_DSL_SPEC_INVALID", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SOURCE_DSL_LOCATION_INVALID", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("MAP_DSL_SPEC_INVALID", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("MAP_DSL_COMPILE_INVALID", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("NORMALIZE_DSL_SPEC_INVALID", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("NORMALIZE_DSL_COMPILE_INVALID", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("ENRICH_DSL_SPEC_INVALID", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("ENRICH_DSL_TEMPLATE_INVALID", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("ENRICH_DSL_COMPILE_INVALID", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("ENRICH_DSL_LOOKUP_PROVIDER_MISSING", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("ENRICH_DSL_LOOKUP_KEY_OP_FAILED", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("ENRICH_DSL_MERGE_POLICY_INVALID", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("DICT_DSL_REGISTRY_INVALID", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("DICT_DSL_SPEC_INVALID", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("DICT_SOURCE_READ_FAILED", SystemErrorCode.IO_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("DICT_SOURCE_MANIFEST_MISSING", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("DICT_SOURCE_MANIFEST_INVALID", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("DICT_SOURCE_FINGERPRINT_MISMATCH", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("DICT_SCHEMA_INVALID", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("DICT_SOURCE_EMPTY", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.WARNING),
        CatalogEntry("DICT_RUNTIME_INIT_FAILED", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("VALIDATE_DSL_SPEC_INVALID", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("MATCH_DSL_SPEC_INVALID", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("MATCH_DSL_COMPILE_INVALID", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("RESOLVE_DSL_SPEC_INVALID", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("RESOLVE_DSL_COMPILE_INVALID", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SINK_DSL_SPEC_INVALID", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("REQUIRED_FIELD_MISSING", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SINK_REQUIRED_MISSING", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SINK_TYPE_INVALID", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("MATCH_IDENTITY_MISSING", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("MATCH_CONFLICT_TARGET", SystemErrorCode.CONFLICT, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("MATCH_CONFLICT", SystemErrorCode.CONFLICT, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("MATCH_CONFLICT_SOURCE", SystemErrorCode.CONFLICT, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("MATCH_DUPLICATE_SOURCE", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.WARNING),
        CatalogEntry("RESOLVE_AMBIGUOUS", SystemErrorCode.CONFLICT, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("RESOLVE_CONFLICT", SystemErrorCode.CONFLICT, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("RESOLVE_TARGET_ID_MISSING", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("RESOLVE_CONFIG_MISSING", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("RESOLVE_MAX_ATTEMPTS", SystemErrorCode.CONFLICT, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("RESOLVE_PENDING", SystemErrorCode.CONFLICT, severity=DiagnosticSeverity.WARNING),
        CatalogEntry("RESOLVE_EXPIRED", SystemErrorCode.CONFLICT, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("CACHE_ERROR", SystemErrorCode.CACHE_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("CACHE_DSL_REGISTRY_INVALID", SystemErrorCode.CACHE_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("CACHE_DSL_SPEC_INVALID", SystemErrorCode.CACHE_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("CACHE_DSL_DEP_CYCLE", SystemErrorCode.CACHE_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("CACHE_DSL_DEP_MISSING", SystemErrorCode.CACHE_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("CACHE_DSL_HASH_MISMATCH", SystemErrorCode.CACHE_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("CACHE_SCHEMA_ENSURE_FAILED", SystemErrorCode.CACHE_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("CACHE_SCHEMA_REBUILD_FAILED", SystemErrorCode.CACHE_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("settings.source.config_read_failed", SystemErrorCode.IO_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("settings.parse.invalid_value", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("settings.validation.range", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("settings.validation.enum", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("settings.conflict.api_credentials", SystemErrorCode.CONFLICT, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("settings.unknown_key", SystemErrorCode.DATA_INVALID, severity=None),
        CatalogEntry("ENRICH_FATAL_POLICY_UNSET", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.WARNING),
        CatalogEntry("ENRICH_MULTI_TARGET_UNSUPPORTED", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("ENRICH_MISSING_KEY", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("ENRICH_PROVIDER_ERROR", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("ENRICH_NO_CANDIDATES", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.WARNING),
        CatalogEntry("ENRICH_AMBIGUOUS", SystemErrorCode.CONFLICT, severity=DiagnosticSeverity.WARNING),
        CatalogEntry("ENRICH_TARGET_MISMATCH", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SECRET_MATCH_KEY_MISSING", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SECRET_STORE_ERROR", SystemErrorCode.IO_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SECRET_REQUIRED", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SECRET_NOT_FOUND", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SECRET_READ_ERROR", SystemErrorCode.IO_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SECRET_DECRYPTION_ERROR", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SECRET_INTEGRITY_ERROR", SystemErrorCode.DATA_INVALID, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("VAULT_STARTUP_KEY_CONFIG_ERROR", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("VAULT_STARTUP_KEY_VALIDATION_ERROR", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("VAULT_STARTUP_PROBE_CORRUPTED", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("VAULT_STARTUP_STORAGE_READONLY", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("VAULT_STARTUP_UNINITIALIZED_READONLY", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("INVALID_JSON", SystemErrorCode.IO_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("INVALID_ITEMS_FORMAT", SystemErrorCode.IO_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("NETWORK_ERROR", SystemErrorCode.INFRA_UNAVAILABLE, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("MAX_PAGES_EXCEEDED", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("TARGET_ID_CONFLICT", SystemErrorCode.CONFLICT, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("INTERNAL_ERROR", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("UNEXPECTED_ERROR", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("API_ERROR", SystemErrorCode.INTERNAL_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SINK_HTTP_ERROR", SystemErrorCode.INFRA_UNAVAILABLE, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SINK_TIMEOUT", SystemErrorCode.INFRA_TIMEOUT, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SINK_IO_ERROR", SystemErrorCode.IO_ERROR, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SINK_UNAVAILABLE", SystemErrorCode.INFRA_UNAVAILABLE, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SINK_UNAUTHORIZED", SystemErrorCode.AUTH_UNAUTHORIZED, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SINK_FORBIDDEN", SystemErrorCode.AUTH_FORBIDDEN, severity=DiagnosticSeverity.ERROR),
        CatalogEntry("SINK_CONFLICT", SystemErrorCode.CONFLICT, severity=DiagnosticSeverity.ERROR),
    ]
    return ErrorCatalog(entries, strict=strict)
